http://localhost:5000/api/v1/companies

###
http://localhost:5000/api/v1/companies/2

###

POST http://localhost:5000/api/v1/companies
Content-Type: application/json

{
  "name": "WIIT TRAINING",
  "zip_code": "64100",
  "city": "BAYONNE"
}

###
PUT http://localhost:5000/api/v1/companies/1
Content-Type: application/json

{
  "zip_code": "12345"
}


###
DELETE http://localhost:5000/api/v1/companies/1
Content-Type:  application/json
