GET http://localhost:5000/api/v1/professions

###

GET http://localhost:5000/api/v1/professions/3

###

POST http://localhost:5000/api/v1/professions HTTP/1.1
content-type: application/json

{
    "name": "Junior"
}

###

PUT http://localhost:5000/api/v1/professions/3 HTTP/1.1
content-type: application/json

{
    "name": "charcutier"
}

###

DELETE http://localhost:5000/api/v1/professions/1 HTTP/1.1
content-type: application/json

{

}