GET http://localhost:5000/api/v1/projects HTTP/1.1

###
GET http://localhost:5000/api/v1/projects/2798e00c-0d0d-4f06-9749-0550c4765a9e HTTP/1.1


###
POST http://localhost:5000/api/v1/projects HTTP/1.1
Content-Type: application/json

{
        "name": "CrockMou",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi pretium gravida placerat. In mattis hendrerit magna gravida vehicula. Duis iaculis elit a neque mattis laoreet. Proin enim nibh, luctus nec elementum vel, pulvinar at tellus. Vestibulum vel laoreet turpis, ut eleifend est. Pellentesque sit amet nisl sit amet odio ultrices rhoncus nec sed lacus.",
        "code": "Ceci est un code",
        "companyId": "500c8dbd-ee35-44dc-92c9-a3598b9f9d63",
        "taxation": "CII"
}

###
POST http://localhost:5000/api/v1/projects HTTP/1.1
Content-Type: application/json

{
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi pretium gravida placerat. In mattis hendrerit magna gravida vehicula. Duis iaculis elit a neque mattis laoreet. Proin enim nibh, luctus nec elementum vel, pulvinar at tellus. Vestibulum vel laoreet turpis, ut eleifend est. Pellentesque sit amet nisl sit amet odio ultrices rhoncus nec sed lacus.",
        "code": "Ceci est un code",
        "companyId": "500c8dbd-ee35-44dc-92c9-a3598b9f9d63",
        "taxation": "CII"
}
// name field missing : should respond with status 400

###
PUT http://localhost:5000/api/v1/projects/65030405-994e-41f4-8468-d3716617205b HTTP/1.1
Content-Type: application/json

{
        "name": "La rive des dragons"
}

###
PUT http://localhost:5000/api/v1/projects/65030405-994e-41f4-8468-d3716617205b HTTP/1.1
Content-Type: application/json

{
        "description": "ceci est une description"
}

###
DELETE http://localhost:5000/api/v1/projects/65030405-994e-41f4-8468-d3716617205b HTTP/1.1

###
POST http://localhost:5000/api/v1/projects/0e9dbd62-a489-47ea-9f10-39f578c1a568/users/2e4a0e05-97c0-4017-b49f-b0e07a0172e2

###
DELETE http://localhost:5000/api/v1/projects/0e9dbd62-a489-47ea-9f10-39f578c1a568/users/2e4a0e05-97c0-4017-b49f-b0e07a0172e2


