http://localhost:5000/api/v1/statuses

###
http://localhost:5000/api/v1/statuses/2

###
POST http://localhost:5000/api/v1/statuses
Content-Type: application/json

{"name":"EURL"}

###
PUT http://localhost:5000/api/v1/statuses/3
Content-Type: application/json

    {"name": "SA"}