http://localhost:5000/api/v1/status

###
http://localhost:5000/api/v1/status/2

###
POST http://localhost:5000/api/v1/status
Content-Type: application/json

{"name":"EURL"}

###
PUT http://localhost:5000/api/v1/status/2
Content-Type: application/json

    {"name": "SA"}