GET http://localhost:5000/api/v1/users HTTP/1.1

###
GET http://localhost:5000/api/v1/users/4e54a598-3997-40b8-bb29-fe5908f98dea HTTP/1.1

###
POST http://localhost:5000/api/v1/users HTTP/1.1
content-type: application/json

{
    "firstName": "Aer",
    "lastName": "yle",
    "email": "aeryle@aeryle.fr",
    "role": "SUPERADMIN",
    "password": "pass",
    "jobId": "0faed827-d4ee-495a-a50a-b074c05b5bb7"
}

###
POST http://localhost:5000/api/v1/users HTTP/1.1
content-type: application/json

{
    "firstName": "Marc",
    "lastName": "Dupond",
    "email": "mar@test.fr",
    "jobId": "5f57d0c8-5f87-4fb3-9238-3d53bbb73218"
}

###
POST http://localhost:5000/api/v1/users HTTP/1.1
content-type: application/json

{
    "firstName": "Marc",
    "lastName": "Dupond",
    "email": "mar@test.fr"
}
// should respond with 422

###
PUT http://localhost:5000/api/v1/users/2618ab26-aa04-4752-a233-6a8e0a23bde4 HTTP/1.1
content-type: application/json

{
    "role": "ADMIN",
    "companyId": "d3a0a404-5e64-450c-8aa1-1ca98cb7e141"
}

###
PUT http://localhost:5000/api/v1/users/2618ab26-aa04-4752-a233-6a8e0a23bde4 HTTP/1.1
content-type: application/json

{
    "role": "USER",
    "jobId": "5e2c2efc-c1f9-43ef-a2ce-26edbf2f8d77",
    "companyId": null
}
//should disconnect company

###
PUT http://localhost:5000/api/v1/users/2 HTTP/1.1
content-type: application/json

{
    "role": "SUPERADMIN",
    "jobId": "5e2c2efc-c1f9-43ef-a2ce-26edbf2f8d77",
    "companyId": "d3a0a404-5e64-450c-8aa1-1ca98cb7e141"
}
//Should respond 404 not found

###
DELETE http://localhost:5000/api/v1/users/2 HTTP/1.1
// should respond 404 "Not found"

###
DELETE http://localhost:5000/api/v1/users/9944d537-435b-4504-bb0e-766430ba2b26 HTTP/1.1

###
POST http://localhost:5000/api/v1/users/fedf4d52-1c95-4b0a-b955-db19d79fe166/projects/0e9dbd62-a489-47ea-9f10-39f578c1a568

###
DELETE http://localhost:5000/api/v1/users/fedf4d52-1c95-4b0a-b955-db19d79fe166/projects/0e9dbd62-a489-47ea-9f10-39f578c1a568
//should update(delete) the project of user ID
