GET http://localhost:5000/api/v1/users HTTP/1.1

###
GET http://localhost:5000/api/v1/users/2 HTTP/1.1

###
POST http://localhost:5000/api/v1/users HTTP/1.1
content-type: application/json

{
    "firstname": "Basile",
    "lastname": "Vernouillet",
    "email": "formateur@test.fr",
    "role": "SUPER_ADMIN",
    "jobs": "",
    "company_id": null
}

###
PUT http://localhost:5000/api/v1/users/4 HTTP/1.1
content-type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "formateur@test.fr",
    "role": "SUPER_ADMIN",
    "jobs": "nettoyeur",
    "company_id": null
}

###
DELETE http://localhost:5000/api/v1/users/2 HTTP/1.1
